### ISSUE TITLE
Player Arrow on Minimap looks broken

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/Minimap#31]
The pointer for the player on the minimap is supposed to be an arrow, but it actually is a glitchy black bar.

![image](https://user-images.githubusercontent.com/1448874/131260469-678dad64-a625-42f1-a92b-087b0277dabf.png)

Appeared on https://github.com/MovingBlocks/Terasology/releases/tag/v5.2.0-rc.1 and earlier releases.

**Comment by keturn** [comment]
To clarify, the included screenshot is from v5.2.0-rc.1, but this not a regression new to 5.2. It was the same in 5.1 and perhaps earlier.

**Comment by mohamedation** [comment]
i did a PR that fixes that displays the arrow, but might not be the correct solution. could shed some light on the issue.
https://github.com/Terasology/Minimap/pull/33

**Comment by jdrueckert** [comment]
Fixed by #33
